### ISSUE TITLE
Windows hosts need IPv6 localhost for vhosts to work

### ISSUE THREAD

**Issue by jan-clr** [jonas-kell/wsl-webdevelopment#1]
Could not connect to the domain specified in the vhost configuration under windows, with port forwarding enabled or not even though it was reachable from within wsl. This was fixable by adding the IPv6 localhost to the windows hosts file

```
# Microsoft stuff....
# Found at C:\Windows\System32\drivers\etc\hosts

127.0.0.1 localhost
127.0.0.1 <your-dev-site-name>
::1 <your-dev-site-name>
```

Solution from [this post](https://superuser.com/questions/1583304/vhost-not-norking-on-wsl2).

**Comment by jonas-kell** [comment]
Magst du nen pull request machen dann znd das noch kommentieren irgendwie in dem main-file?Am 13.09.2021 14:23 schrieb Jayc33 ***@***.***>:
Could not connect to the domain specified in the vhost configuration under windows, with port forwarding enabled or not even though it was reachable from within wsl. This was fixable by adding the IPv6 localhost to the windows hosts file
# Microsoft stuff....
# Found at C:\Windows\System32\drivers\etc\hosts

127.0.0.1 localhost
127.0.0.1 <your-dev-site-name>
::1 <your-dev-site-name>

Solution from this post.
